-- RSVP confirmations table for Baby Shower app
create table if not exists public.confirmaciones (
  id bigint generated by default as identity primary key,
  "timestamp" timestamptz not null default now(),
  invitado_id integer,
  nombre text not null,
  familia text,
  asistencia text not null check (asistencia in ('si', 'no')),
  personas integer not null default 0 check (personas >= 0),
  mensaje text not null default '',
  origen text not null default 'web-baby-shower',
  ip text not null default '',
  user_agent text not null default '',
  created_at timestamptz not null default now()
);

alter table public.confirmaciones enable row level security;

-- Allow guests to submit RSVP records from the public site
drop policy if exists "allow public insert confirmaciones"
on public.confirmaciones;

create policy "allow public insert confirmaciones"
on public.confirmaciones
for insert
to anon, authenticated
with check (true);

-- Keep read/update/delete disabled for public users

grant usage on schema public to anon, authenticated;
grant insert on table public.confirmaciones to anon, authenticated;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where c.relkind = 'S'
      and n.nspname = 'public'
      and c.relname = 'confirmaciones_id_seq'
  ) then
    grant usage, select on sequence public.confirmaciones_id_seq to anon, authenticated;
  end if;
end $$;
